# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # Needed to interact with GitHub releases (to upload the JAR)
      packages: write       # Optional, if you also need to interact with packages
      id-token: write       # Necessary for interacting with GitHub API in private repos

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17 (Ubuntu)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven (Ubuntu)
      run: mvn clean package -DskipTests

    - name: Delete JAR file containing "original" (Ubuntu)
      run: |
        find target -name "*original*.jar" -exec rm -f {} \;

    - name: Rename JAR file (Ubuntu)
      run: |
        for file in target/*.jar; do
          mv "$file" "${file%.jar}-ubuntu.jar"
        done

    - name: Upload JAR to GitHub Release (Ubuntu)
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write       # Needed to interact with GitHub releases (to upload the JAR)
      packages: write       # Optional, if you also need to interact with packages
      id-token: write       # Necessary for interacting with GitHub API in private repos

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17 (Windows)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven (Windows)
      run: mvn clean package -DskipTests

    - name: Delete JAR file containing "original" (Windows)
      run: |
        Remove-Item -Path target\*original*.jar -Force
      shell: pwsh

    - name: Rename JAR file (Windows)
      run: |
        Get-ChildItem target\*.jar | Rename-Item -NewName { $_.BaseName + "-windows.jar" }
      shell: pwsh

    - name: Upload JAR to GitHub Release (Windows)
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
