# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write       # Needed to interact with GitHub releases (to upload the JAR)
      packages: write       # Optional, if you also need to interact with packages
      id-token: write       # Necessary for interacting with GitHub API in private repos

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Delete JAR file containing "original"
      run: |
        find target -name "*original*.jar" -exec rm -f {} \;

    - name: Upload JAR to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
        tag_name: ${{ github.job }}  # Use the tag name that triggered the release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}\
  
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write       # Needed to interact with GitHub releases (to upload the JAR)
      packages: write       # Optional, if you also need to interact with packages
      id-token: write       # Necessary for interacting with GitHub API in private repos

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17 (Windows)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven (Windows)
      run: mvn clean package -DskipTests

    - name: Delete JAR file containing "original" (Windows)
      run: |
        del /f /q target\*original*.jar
      shell: pwsh  # Use PowerShell shell to delete file on Windows

    - name: Upload JAR to GitHub Release (Windows)
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
        tag_name: ${{ github.job }}  # Use the tag name that triggered the release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
